import DashboardInitialView from "@/components/DashboardInitialView/DashboardInitialView";
import DashboardLayout from "@/components/DashboardLayout/DashboardLayout";
import Head from "next/head";
import React from "react";

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <DashboardInitialView />
      </>
    </>
  );
};

export default Dashboard;

Dashboard.getLayout = function getLayout(page) {
  return <DashboardLayout>{page}</DashboardLayout>;
};
