import Head from "next/head";
import Homepage from "@/components/Homepage/Homepage";
import Layout from "@/components/Layouts/Layout";
export default function Home() {
  return (
    <>
      <Head>
        <title>Go Eventy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Homepage />
      </main>
    </>
  );
}
Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
